define_property(GLOBAL PROPERTY OMNIMON_TARGETS
  BRIEF_DOCS "OmniMon targets"
  FULL_DOCS "List of all non-ASan OmniMon targets for dual-variant mapping"
)

function(omnimon_add_library name)
  set(is_interface FALSE)
  foreach(arg ${ARGN})
    if(arg STREQUAL "INTERFACE")
      set(is_interface TRUE)
    endif()
  endforeach()

  # Always append to the target registry for mapping purposes
  set_property(GLOBAL APPEND PROPERTY OMNIMON_TARGETS ${name})

  if(OMNIMON_BUILD_STANDARD OR is_interface)
    add_library(${name} ${ARGN})
  endif()
  
  if(OMNIMON_BUILD_ASAN AND NOT is_interface)
    add_library(${name}-asan ${ARGN})
    target_compile_options(${name}-asan PUBLIC "-fsanitize=address" "-fno-omit-frame-pointer")
    target_link_options(${name}-asan PUBLIC "-fsanitize=address")
  endif()
endfunction()

function(omnimon_add_executable name)
  # Always append to the target registry for mapping purposes
  set_property(GLOBAL APPEND PROPERTY OMNIMON_TARGETS ${name})

  if(OMNIMON_BUILD_STANDARD)
    add_executable(${name} ${ARGN})
  endif()
  
  if(OMNIMON_BUILD_ASAN)
    add_executable(${name}-asan ${ARGN})
    target_compile_options(${name}-asan PRIVATE "-fsanitize=address" "-fno-omit-frame-pointer")
    target_link_options(${name}-asan PRIVATE "-fsanitize=address")
  endif()
endfunction()

function(omnimon_target_link_libraries target)
  if(OMNIMON_BUILD_STANDARD AND TARGET ${target})
    target_link_libraries(${target} ${ARGN})
  endif()
  
  if(OMNIMON_BUILD_ASAN AND TARGET ${target}-asan)
    get_property(omnimon_targets GLOBAL PROPERTY OMNIMON_TARGETS)
    set(mapped_args "")
    foreach(arg ${ARGN})
      set(mapped_arg ${arg})
      list(FIND omnimon_targets "${arg}" index)
      if(NOT index EQUAL -1)
        set(mapped_arg "${arg}-asan")
      endif()
      list(APPEND mapped_args "${mapped_arg}")
    endforeach()
    target_link_libraries(${target}-asan ${mapped_args})
  endif()
endfunction()

function(omnimon_target_include_directories target)
  if(OMNIMON_BUILD_STANDARD AND TARGET ${target})
    target_include_directories(${target} ${ARGN})
  endif()
  if(OMNIMON_BUILD_ASAN AND TARGET ${target}-asan)
    target_include_directories(${target}-asan ${ARGN})
  endif()
endfunction()

function(omnimon_target_compile_options target)
  if(OMNIMON_BUILD_STANDARD AND TARGET ${target})
    target_compile_options(${target} ${ARGN})
  endif()
  if(OMNIMON_BUILD_ASAN AND TARGET ${target}-asan)
    target_compile_options(${target}-asan ${ARGN})
  endif()
endfunction()

function(omnimon_add_test)
  set(test_name "")
  set(test_command "")
  set(state "")
  foreach(arg ${ARGV})
    if(arg STREQUAL "NAME")
      set(state "NAME")
    elseif(arg STREQUAL "COMMAND")
      set(state "COMMAND")
    else()
      if(state STREQUAL "NAME")
        set(test_name ${arg})
        set(state "")
      elseif(state STREQUAL "COMMAND")
        set(test_command ${arg})
        set(state "")
      endif()
    endif()
  endforeach()

  if(OMNIMON_BUILD_STANDARD)
    add_test(${ARGV})
  endif()
  
  if(OMNIMON_BUILD_ASAN AND test_name AND test_command)
    add_test(NAME ${test_name}-asan COMMAND ${test_command}-asan)
  endif()
endfunction()
